# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb881a582c5e88a7f6c205cdd6b12a6f170bb07bf1fe3c44698491340139f909c58160a35d6e22254fda36da555ebc876af76da146516376f0e7a82749f1d8db

test:
  secret_key_base: f1ec27702f8b1fd3627f36b57b28ac5b28fa37022939afb1b978b4e565051e726f04ce3d9e5d290b8f8874ce00027ccf9faaccbb3a6ebdcf1850249b1aaa8265

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
